name: Release
on:
    push:
        tags:
            - '*'
jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        permissions:
          contents: read
          id-token: write
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
            - run: bun install
            - name: Build
              run: bun run build
            - name: Publish
              run: npm publish --access public --provenance
              env:
                NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
